language: python

python:
  - 3.7

before_install:
  - pip install -U pip
  - pip install pipenv codecov

install:
  - pipenv install --system --dev --deploy

before_script: cd src

script:
  - python manage.py migrate
  - coverage run manage.py test

after_success:
  - codecov
